# Generated by Django 2.1.7 on 2019-03-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('type_options_req', models.IntegerField(default=0)),
                ('type_options_multiple', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('readable_name', models.CharField(max_length=200)),
                ('field_options', models.CharField(blank='true', default='', max_length=255)),
                ('field_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.FieldType')),
            ],
            options={
                'ordering': ['readable_name'],
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['risk_name'],
            },
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risk_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskType'),
        ),
    ]
