# Generated by Django 2.1.7 on 2019-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='type_options_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='type_options_req',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='field_options',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
