# Generated by Django 2.1.7 on 2019-03-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20190321_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='type_options_multiple',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='type_options_req',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
