# Generated by Django 2.1.7 on 2019-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20190321_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='type_options_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='type_options_req',
            field=models.BooleanField(default=False),
        ),
    ]
